### ISSUE TITLE
RPO Count not updated

### ISSUE THREAD

**Issue by johndcollins** [CANopenNode/CANopenEditor#10]
I added more RPOs, but the count on the Device Info stays at 4, shouldn't this increase as I add more RPOs?
![Example3](https://user-images.githubusercontent.com/1684130/129274080-7a40bebe-abde-4055-8728-3a448f527c73.JPG)
![Example4](https://user-images.githubusercontent.com/1684130/129274084-2aa61405-fceb-4feb-958d-2cb9e845edad.JPG)

**Comment by trojanobelix** [comment]
Fixed in e6cb85dc10eb7bd8f4566f4c5ac6c510e47be835 (bugfix branch)
