### ISSUE TITLE
Reopened network file crashes during saving

### ISSUE THREAD

**Issue by Inviz** [CANopenNode/CANopenEditor#11]
Hello. It is possible to save network file once, but then opening it and saving will crash (seems like getting current directory path and normalizing it throws). 

Windows 10.

**Comment by trojanobelix** [comment]
should be fixed in d834fa412cab9aa895c25e3fe0e591771690e248

**Comment by Inviz** [comment]
thank you, great news

**Comment by trojanobelix** [comment]
A test and feedback would be helpful. Thank you.
