### ISSUE TITLE
Convert default profiles to xpd files

### ISSUE THREAD

**Issue by nimrof** [CANopenNode/CANopenEditor#116]
Without XML Support the default profiles DSP302-NMTMaster.xml and DS301_profile_old.xml can`t be used anymore.
They should be converted to a xpd-file

_Originally posted by @trojanobelix in https://github.com/CANopenNode/CANopenEditor/pull/101#issuecomment-2202641005_

**Comment by CANopenNode** [comment]
I would delete those two profiles and add DS401_profile.xpd, which is missing at the binaries.

At least DSP302-NMTMaster.xml, I think it is not usable. If DS301_profile_old.xml has some usability, it should be verified first and renamed appropriately.
