### ISSUE TITLE
HighLimit and LowLimit

### ISSUE THREAD

**Issue by NebulaDev16** [CANopenNode/CANopenEditor#12]
With each and every OD entry (Index and subindex) combination, there are additional attributes which can be set by the user.
![image](https://user-images.githubusercontent.com/89458942/138250343-515557ef-d480-41ba-b1af-f34b95a11f78.png)

What is the significance and need of these additional object settings?

For example, we have tried to set high and low limit on one OD entry and when we are trying to generate OD.c/OD.h from it, this information is not associated with the OD entry at all !! 

XDD file has these values as 
                
![image](https://user-images.githubusercontent.com/89458942/138254151-7f6edd31-fd4a-4f38-9fc1-f4ef8df2b2fb.png)

Do we have corresponding structures in CANOpenNode to ingest and validate while doing SDO/PDO transactions wrt min and maximum value?

**Comment by trojanobelix** [comment]
The high and low limit values are optional parameters eg. for the EDS file (see CiA Draft Standard Proposal 306)
