### ISSUE TITLE
Support .Net8 as LTS?

### ISSUE THREAD

**Issue by trojanobelix** [CANopenNode/CANopenEditor#145]
I have created a net8 Branch for testing. Because it is the next LTS version it might make sense to support it. Seems not to be a big think. @nimrof  @CANopenNode 
Should we or not?

**Comment by nimrof** [comment]
Good initiative.
Yes we should.
.net6 has end-of-life in a few days (12. November) and .net8 is the next logical step.
So maybe we should just replace .net6 with .net8?

**Comment by trojanobelix** [comment]
Here are the few rough edges I found during the conversion:

- I didn't manage to add 8 to the 4.8 and 6 project. But I didn't bother because I just wanted to see what was needed for 8. 
- The sourcegrid is again maintained by Siemens (https://github.com/siemens/sourcegrid) and is 8. compatible. However, earlier .net versions are no longer supported.
- The Siemens sourcegrid NuGet packet sources are on Github and I have problems to authenticate myself (TOKEN fits...)
- .8 does not allow the use of names like ‘file’ in ‘public file file’ 

Mainly these are problems with the toolchain, the rest seems to be compatible with a few changes

**Comment by nimrof** [comment]
> Here are the few rough edges I found during the conversion:
> 
> - I didn't manage to add 8 to the 4.8 and 6 project. But I didn't bother because I just wanted to see what was needed for 8.

I can fix, if you want :), but it might be easier to start from scratch to avoid unnecessary changes the migration does

> - The sourcegrid is again maintained by Siemens (https://github.com/siemens/sourcegrid) and is 8. compatible. However, earlier .net versions are no longer supported.
> - The Siemens sourcegrid NuGet packet sources are on Github and I have problems to authenticate myself (TOKEN fits...)

Dont think we need to change that, cant we use the same we use for .net 6?

> - .8 does not allow the use of names like ‘file’ in ‘public file file’ 

We can just rename it to File.

> Mainly these are problems with the toolchain, the rest seems to be compatible with a few changes 

👍

**Comment by trojanobelix** [comment]
In any case, start from the beginning!  I think you can do it in a few minutes! I'm more of an embedded nerd and use 9 commits to do very simple things in C# :-)

**Comment by trojanobelix** [comment]
We do not need to change to Siemens jet. But the old package one is really old, l and I do lieke a maintained source. But no need to hurry, if it is not easy to use different packages with different .net versions.

**Comment by nimrof** [comment]
> In any case, start from the beginning! I think you can do it in a few minutes! I'm more of an embedded nerd and use 9 commits to do very simple things in C# :-)

take a look at #146
I mostly do embedded c/c++ at work, but c# is just so much better for web/gui if you do not have to share much code. 

> We do not need to change to Siemens jet. But the old package one is really old, l and I do lieke a maintained source. But no need to hurry, if it is not easy to use different packages with different .net versions.

Agree its old, but hopefully its will hold until the new gui is done🤞

**Comment by trojanobelix** [comment]
From my point of view: Merge!

**Comment by nimrof** [comment]
> From my point of view: Merge!

Then feel free to approve it :D
