### ISSUE TITLE
Adding new RX PDO does nothing!

### ISSUE THREAD

**Issue by sudoDavi** [CANopenNode/CANopenEditor#16]
When I press the Add new PDO in the RX PDO Mapping nothing happens.
The only change is that the Available Objects for PDO gets a slide bar.

I'm using the latest Windows build.

*Before pressing the button*
![image](https://user-images.githubusercontent.com/12603499/142629933-61404882-ef33-4d4c-a7b4-3acf15efd7c4.png)

*After pressing the button*
![image](https://user-images.githubusercontent.com/12603499/142630006-52db9701-93ae-4183-8ca4-b3d4fabbdeee.png)

This happens in any project, be it a new empty one or a populated one like demoDevice from CANopenDemo

*After pressing the button nothing happens*
![image](https://user-images.githubusercontent.com/12603499/142630217-7b7cc065-cfe8-46fd-973c-5b0252b6e246.png)

**Comment by koson** [comment]
Hi, look like you cannot add RPDO more than four?
  
On this issue, I use the cloning method from the existing RPDO.
Go to the Object Dictionary tab, right-click on the line "0x1403 RPDO communication parameter" and select "clone..." then edit anything you need. The same procedure on "0x1603 RPDO mapping parameter".

FYI: you can make a selection on 0x1403 and 0x1603 then clone both of them. 

Take a look at the tab RX RPDO mapping, you'll see the addition RPDO.

I don't know how to fix this by programming.

**Comment by trojanobelix** [comment]
Should be fixed with [4851453](https://github.com/CANopenNode/CANopenEditor/commit/48514531f83847606986d6e2acfb59f51b821651)
