### ISSUE TITLE
Previous version of the application

### ISSUE THREAD

**Issue by CarmenMFM** [CANopenNode/CANopenEditor#17]
Hi!

I worked with this tool a few months ago and now I need to use it again but the files it generates have been updated and I would not like to update my project.

 Does anyone have the previous executable?

Thanks you!

**Comment by Regelink** [comment]
If you fork the project and adjust .github/workflows/dotnet.yml to checkout the specific revision you want to build, you can have GitHub to perform the workflow and produce the binaries for you.
