### ISSUE TITLE
Out of index fault in OD export

### ISSUE THREAD

**Issue by p139933** [CANopenNode/CANopenEditor#20]
There is out of index fault when exporting OD to  CanOpenNode V4. Error is in Make_cname function and happen when parameter name starts with single letter followed by white space (for example "X axis"), at code line 694 ( else if (Char.IsLower(tok[1])) access out of string length.

**Comment by Regelink** [comment]
I think this is fixed in #5

**Comment by trojanobelix** [comment]
should be fixed in fdb0a09935c881a352cf3fff5f975afb6642275a
