### ISSUE TITLE
Editor created OD.c does not compile

### ISSUE THREAD

**Issue by xenpac** [CANopenNode/CANopenEditor#23]
when using the standard Canopennode example DS301_profile.eds file with the editor and export canopen OD.h/c, i get compile errors.

This also happened when modifying things in my project.

So, editor not usable!

**Comment by HamedJafarzadeh** [comment]
Hey,

You might want to give my forked version a try. It is working fine for me.

[https://github.com/HamedJafarzadeh/CANopenEditor](https://github.com/HamedJafarzadeh/CANopenEditor)

**Comment by xenpac** [comment]
hi, almost.
seems that the   Counters of OD objects on top of od.h are partly missing.  (doing a fil compare)

**Comment by xenpac** [comment]
![image](https://user-images.githubusercontent.com/28014826/171989671-1dcc4437-fb72-4ec7-ae96-242fe4ffdc30.png)

**Comment by xenpac** [comment]
I solve my own issue:

This canopen editor only works correct, if you use the .xpd  config file format.
with .xdd, .eds, .dcf,  it will NOT work !!!

**Comment by trojanobelix** [comment]
Can you please run a test and provide me with the erroneous od.c output and a working file for a file comparison? And of cause the xdd
