### ISSUE TITLE
Mapping issue II

### ISSUE THREAD

**Issue by trojanobelix** [CANopenNode/CANopenEditor#28]
1. Changes in the PDOview list (e.g. COB-ID) are not reflected in the textBox.

Example: The  selected item (0x1801) in the PDOview list the COB_ID been changed to "180". In the textbox has still the old value of 180.

![image](https://user-images.githubusercontent.com/15106425/173002986-ceb037b2-9034-4610-9c1b-87859f85932c.png)

2. Pressing the "Save" button does not save the changes made in the textBoxes or in the PDOview list.
The changes will be lost.

Example:
If you change the COB-ID in the  PDOview list and in the textBox from 280 to 180 after pressing the "Save" button both values are changed to the old value of 280 instead of saving the new value (180) 

Before ( COB ID of 1801 is 280 ):
![image](https://user-images.githubusercontent.com/15106425/173005184-80cf78cc-c93e-4bd9-aceb-47b818e90b50.png)

Change COB ID of 1801 to 180 (TextBox and PDOview)
![image](https://user-images.githubusercontent.com/15106425/173005011-f1fb5085-38ff-46ae-a480-4f6ac2ff6cb7.png)

After "Save"  ( COB ID of 1801 is 280 again):
![image](https://user-images.githubusercontent.com/15106425/173005337-3c20e786-30ae-464e-a2c3-de1480fdef58.png)

**Comment by xenpac** [comment]
Does anybody know an alternate opensource editor that works ?

**Comment by trojanobelix** [comment]
Should be fixed with [4851453](https://github.com/CANopenNode/CANopenEditor/commit/48514531f83847606986d6e2acfb59f51b821651)
