### ISSUE TITLE
Object Dictionary GUI Table Display Issue

### ISSUE THREAD

**Issue by bennettbe** [CANopenNode/CANopenEditor#3]
Encountered an issue on windows 10 where the Object Dictionary GUI's tables did not size properly. Resizing the window did not solve this problem.

<img width="601" alt="ErrorResizeIssue" src="https://user-images.githubusercontent.com/87715493/126400442-cc7c3068-441a-4647-b097-1f1b32dae3f3.PNG">

**Comment by trojanobelix** [comment]
fixed in 65eb20f3c403129708db67ee3146b4cce7060321
