### ISSUE TITLE
Object Settings under Object Dictionary not present

### ISSUE THREAD

**Issue by rohinidr** [CANopenNode/CANopenEditor#36]
Object Settings does not show up under Object Dictionary . Due to this cannot edit any parameters
Using Visual Studio 2022

<img width="1431" alt="Screen Shot 2022-10-04 at 3 40 07 PM" src="https://user-images.githubusercontent.com/37817230/193935400-e1137867-fd67-4072-beae-8c994b4adcca.png">

**Comment by trojanobelix** [comment]
Please test the last commit of the bugfix. This problem should be fixed.

**Comment by rohinidr** [comment]
Settings menu is works in the new changes
