### ISSUE TITLE
DeviceCommissioning / DeviceComissioning

### ISSUE THREAD

**Issue by trojanobelix** [CANopenNode/CANopenEditor#38]
The DSP302 (V3.2.1) stated:

Device Configuration File
Configuration tools have to know, which device in the network is the CANopen Manager. For
the purpose of designating this manufacturer independent, this information is written into the
DCF files of the project. The section **DeviceComissioning** of each device contains the boolean entry CANopenManager. If the entry is missing, the described device is not the CANopen
Manager.

Some tools (eg. EDSchecker from Vector) use the DSP302 definition [DeviceComissioning]
but some others (e.g. HMS/Ixxat CanAnalyser) use right spelling: [DeviceCommissioning]

The CANopenEditor uses DeviceCommissioning, which satisfied just one variant.

How to make it compatible for both?

**Comment by CANopenNode** [comment]
CANopen XML Schema specifies "DeviceCommissioning":
https://www.can-cia.org/xml/1.1/ProfileBody_Network_CANopen.xsd

But the standard CiA306 specifies [DeviceComissioning] as keyword inside DCF file but standard uses correct spelling inside its explanation text.

I think, CANopenEditor should write [DeviceComissioning] into DCF file as specified by standard. But only into DCF file, leave unchanged elsewhere. I hope HMS/Ixxat CanAnalyser will work.

**Comment by trojanobelix** [comment]
What a mess. As if the CanOpen standard wasn't complicated enough in itself :-)

**Comment by trojanobelix** [comment]
I had already changed everything to "commission" as stated in DSP306 until I realised that not all tools use this definition. Changing only the DCF seems like a good compromise.
