### ISSUE TITLE
Typo in generatd DCF file

### ISSUE THREAD

**Issue by thesummer** [CANopenNode/CANopenEditor#46]
Hello,

I used the CANopenEditor version 4.0-104-g6f50f73 to configure some nodes and generate a coresponding DCF.
In the DCF I noticed that the block with the general device setup is generated as `[DeviceComissioning]` while it should be `[DeviceCommissioning]` (with "mm").

It's a small type, but it prevents for example https://canopen.readthedocs.io/en/latest/ to read in the generated DCF.
I looked for the string in the source code and fix it myself, but couldn't find it.

Do you have any suggestions? It seems to be one of the few parts where it is not possible to rename the field through the GUI.

**Comment by trojanobelix** [comment]
Unfortunately, the standard (DSP302) defines the section with "DeviceCommissioning". Clearly a typo, but unfortunately defined exactly like this. 

This is why the file is written in conformity with the standard. A tool that evaluates this should therefore at least accept this way of writing.

**Comment by thesummer** [comment]
Oh, that is a weird thing. Thanks for the fast reply. I will try to fix it in the Python module then.

**Comment by trojanobelix** [comment]
DSP306  Version 1.1 Date: 29.06.2001 stated
5.3 Device Co**mm**issioning
There is an additional section in the DCF named DeviceCo**m**issioning:
(...)
Example:
[DeviceCo**m**issioning]

**Comment by thesummer** [comment]
I just checked the version 1.3.0 from 2005. The typo with *DeviceComissioning* is still there, but I think I found a smaller thing which is on the CANopenEditor side.

> There shall be an additional section in the DCF named _DeviceComissioning_:
> _NodeID_ shall indicate the device’s address (Unsigned8)
> _NodeName_ shall indicate the node name (max 246 characters)
> _Baud**r**ate_ shall indicate the device’s baudrate (Unsigned16)
> _NetNumber_ shall indicate the number of the network (Unsigned32)
> _NetworkName_ shall indicate the name of the network (max 243 characters)
> 

In a generated DCF with CANopenEditor I got 
```
[DeviceComissioning]
NodeId=1
NodeName=
BaudRate=500
NetNumber=0
NetworkName=
```
So, _NodeI**D**_ and _Baud**r**ate_ seem to be a little off with the capitalization.

**Comment by thesummer** [comment]
Thank you for the fast fix, but where do I find the binaries? Is there a pipeline where I can download the artifacts?

**Comment by trojanobelix** [comment]
> Thank you for the fast fix, but where do I find the binaries? Is there a pipeline where I can download the artifacts?

I release the binaries at irregular intervals, though I have been able to do at least a minimal test cycle.
You have received an email with the binaries

**Comment by thesummer** [comment]
Hm, can't find any email with an archive or a download link in my mailbox. Only the notifications with your replies.

**Comment by trojanobelix** [comment]
[Release_Bugfix_76baf61.zip](https://github.com/CANopenNode/CANopenEditor/files/10793910/Release_Bugfix_76baf61.zip)

**Comment by thesummer** [comment]
Thanks you very much. I can confirm that this fixes the behavior. 

PS: I have got an email from microsoft that your email was put into quarantine. Seems like it flagged the binaries inside the archive.

**Comment by trojanobelix** [comment]
/* Prevent WebKit and Windows mobile changing default text sizes */
    body,
    table,
    td,
    a {
      -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
    }

    /* Remove spacing between tables in Outlook 2007 and up */
    table,
    td {
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }

    /* RESET STYLES */
    img {
      border: 0;
      height: auto;
      line-height: 100%;
      outline: none;
      text-decoration: none;
      -ms-interpolation-mode: bicubic;
    }

    table {
      border-collapse: collapse !important;
    }

    /* iOS BLUE LINKS */
    a[x-apple-data-detectors] {
      color: inherit !important;
      text-decoration: none !important;
      font-size: inherit !important;
      font-family: inherit !important;
      font-weight: inherit !important;
      line-height: inherit !important;
    }

    /* BASE STYLES */
    body {
      height: 100% !important;
      margin: 0 !important;
      padding: 0 !important;
      width: 100% !important;
      background: #E5E5E5;
    }

    h1,
    h2,
    h3,
    h4,
    table,
    td,
    th,
    a,
    p,
    span,
    div,
    i,
    em,
    li,
    ul,
    .img-block,
    img,
    .comment {
      font-family: 'Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Roboto', 'Arial', sans-serif;
    }

    td {
      font-size: 14px;
      line-height: 20px;
      color: #212121;
    }

    a {
      text-decoration: none;
      color: #0078D4;
    }

    em {
      font-style: normal;
      color: #666;
    }

    p {
      margin: 0;
    }

    /* Buttons */
    .btn-primary:hover {
      border-color: #007acc !important;
    }

    .btn-default:hover {
      border-color: #eaeaea !important;
    }

    .btn-primary:active {
      border-color: #005faa !important;
      background: #005faa !important;
    }

    .btn-default:active {
      border-color: #eaeaea !important;
      background: #eaeaea !important;
    }

    /* Images */
    .img-block {
      display: block;
      color: #ccc;
      font-size: 10px;
      max-width: 100%;
    }

    .img-padding {
      padding: 0 20px 0 0;
    }

    .comment {
      color: #333333;
      font-size: 14px;
      border-radius: 5px;
    }

    .comment blockquote {
      color: #666666;
      border-left: 3px solid #a6a6a6;
      padding: 1px 0 1px 15px;
      margin: 12px 0;
    }

    .comment-gfx {
      padding-top: 20px;
    }

    .note {
      font-size: 13px;
    }

    /* INFO TABLE */
    .activity-table {
      display: table;
    }

    .active {
      background: #CEF1DE;
      font-family: 'Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Roboto', 'Arial', sans-serif;
      font-size: 14px;
      color: #333333;
      padding: 2px 4px;
      display: inline-block;
    }

    .inactive {
      background: #eeeeee;
      font-family: 'Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Roboto', 'Arial', sans-serif;
      font-size: 14px;
      text-decoration: line-through;
      color: #666666;
      padding: 2px 4px;
      display: inline-block;
    }

    .row-label {
      font-family: 'Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Roboto', 'Arial', sans-serif;
      font-size: 14px;
      color: #333;
      padding: 2px 4px;
      line-height: 16px;
      text-align: left;
    }

    /* List */
    .num {
      background: #f2f2f2;
      height: 20px;
      padding: 0 7px;
      font-size: 14px;
    }

    .code li {
      font-family: Menlo, Monaco, Consolas, "Courier New", monospace !important;
      font-size: 14px;
      text-align: left;
    }

    span.monospaced {
      font-family: Menlo, Monaco, Consolas, "Courier New", monospace !important;
    }

    .list li {
      padding: 5px;
    }

    .data {
      word-break: break-all;
      font-family: monospace;
    }

    .red {
      color: red;
    }

    ul,
    ol {
      padding: 0 20px;
    }

    ul {
      list-style-type: circle;
    }

    .anchors {
      list-style-type: square;
    }

    ul ul,
    ol ul {
      padding: 0 30px;
    }

    /* Other */
    .author {
      font-size: 13px;
      color: #666;
      font-style: italic;
      padding: 5px 0 0;
    }

    .code {
      padding: 0;
      list-style: none;
      color: #666666;
    }

    .code li {
      font-family: Menlo, Monaco, Consolas, "Courier New", monospace !important;
    }

    .container {
      padding: 0px;
    }

    .content {
      padding: 20px 0px 20px 0px;
    }

    .title a {
      color: #212121 !important;
      text-decoration: none;
    }

    .title a:hover {
      text-decoration: underline;
    }

    /* MOBILE STYLES */
    @media screen and (max-width: 525px) {

      .content {
        padding: 0px !important;
      }

      .header {
        padding: 10px 30px !important;
      }

      .mobile-sm-txt {
        font-size: 14px !important;
      }

      .mobile-sm-txt span {
        display: block;
      }

      /* ALLOWS FOR FLUID TABLES */
      .wrapper {
        width: 100% !important;
        max-width: 100% !important;
      }

      /* ADJUSTS LAYOUT OF LOGO IMAGE */
      .logo img {
        margin: 0 auto !important;
      }

      /* HIDE CONTENT ON MOBILE */
      .mobile-hide {
        display: none !important;
      }

      /* GIVE IMAGES MAX WIDTH SO THEY SQUISH NICE */
      .img-max {
        max-width: 100% !important;
        width: 100% !important;
        height: auto !important;
      }

      /* FULL-WIDTH TABLES */
      .responsive-table {
        width: 100% !important;
      }

      /* UTILITY CLASSES FOR ADJUSTING PADDING ON MOBILE */
      .padding {
        padding: 10px 5% 15px 5% !important;
      }

      .img-padding {
        padding: 0;
      }

      .padding-meta {
        padding: 20px !important;
      }

      .no-padding {
        padding: 0 !important;
      }

      /* CONTENT */
      .comment {
        padding: 16px 22px !important;
      }

      .logo {
        margin: 0 auto;
        padding: 10px 0 10px 5% !important;
      }

      .gfx-promo {
        padding-bottom: 20px;
        width: 40% !important;
      }

      .gfx-promo img {
        width: 100%;
      }

      /* ADJUST BUTTONS ON MOBILE */
      .mobile-button-container {
        margin: 0 auto;
        width: 100% !important;
        margin-bottom: 10px !important;
      }

      .mobile-button {
        padding: 4px !important;
        display: block !important;
      }

      .mobile-promos {
        text-align: center !important;
        padding: 30px !important;
      }

      .foot-logo {
        padding: 5px 0 25px !important;
      }
    }

    /* Extra small device */
    @media screen and (max-width: 413px) {
      body[class="body-padding"] {
        padding: 0 !important;
      }

      /* HIDE CONTENT ON MOBILE */
      td[class="mobile-hide-xs"],
      td[class="mobile-hide-xs comment-gfx"] {
        display: none;
      }

      /* ADJUST BUTTONS ON MOBILE */
      table[class="mobile-button-container"] {
        margin: 0 auto;
        width: 100% !important;
      }
    }

    /* Android fix */
    div[style*="margin: 16px 0;"] {
      margin: 0 !important;
    }


    /* MARKDOWN RENDERING STYLES */
    .markdown-code {
      background-color: #EAEAEA;
    }

    .markdown-table {
      border: 1;
      border-collapse: collapse;
      border-style: solid;
      border-width: thin;
      border-color: #A6A6A6;
      padding: 8px 10px 10px 10px;
    }

    /* FILE-LIST-SPECIFIC STYLES */
    .file-delete {
      text-decoration: line-through;
    }

    /* BODY SPECIFIC STYLES */

    .message-line {
      color: #201F1E;
      font-size: 16px;
      font-weight: 400;
      margin-left: 5px;
    }
  







  
    
      
        
        
          

          
            
              
                
                  
                    
                      
                        
                          
                            

                        

                        
                          




                            
                              
                                
                                  
                                    


                                    
                                  
                                
                              
                            

                          
                        
                      
                    
                  
                
              
            
          

        
      

    
    
    
    
    
      
      
        

        

          
            

              
                
                  
                    


                    
                      
                        
                          
                        
                      

                      
                        
                          
                            
                              
                                Review These Messages
                            
                          
                        
                      
                      
                        


                          

                            
                              
                                
                                  1 messages are being held for you to review as of 2/21/2023 5:22:15 PM (UTC).
                                
                              
                            

                            
                              
                                
                                  Review them within 30 days of the received date by going to the Quarantine page in the Security Center.
                                
                              
                            


                          


                        
                      
                    

                    

                  
                
              

            
          

          
            

              
                
                  
                    


                    
                      
                        
                          Prevented malware messages
                        
                      
                      
                        
                          
                            
                              
                                Sender:
                              
                              
                                ***@***.***
                              

                              
                                 
                              
                                 
                            
                            
                              
                                Subject:
                              
                              
                                AW: [EXTERNAL] [NEWSLETTER] Re: [CANopenNode/CANopenEditor] Typo in generatd DCF file (Issue #46)
                              

                              
                                 
                              
                                 
                            

                            
                              
                                Date:
                              
                              
                                2/21/2023 1:21:23 PM
                              

                              
                                 
                              
                                 
                            

                            
                              
                                
                                  

                                    
                                      
                                        Review Message
                                      
                                    

                                    
                                    

                                    

                                    

                                    
                                      
                                        Request Release
                                      
                                    

                                    
                                    

                                    
                                      
                                        Block Sender
                                      
                                    
                                  
                                
                              
                            
                            
                              
                                 
                              
                                 

                              
                                 
                              
                                 
                            

                          

                        
                      
                    
                    

                    

                  
                
              

            
          

          

          
            
              
                
                  

                    © 2023 Microsoft Corporation. All rights reserved.
                  
                
                
                  
                    
                      Privacy Statement
                  
                

                
                  
                    
                      Acceptable Use Policy

**Comment by CANopenNode** [comment]
Hi,

In the latest standard (2019) there is still:

> 7.3.5 Device commissioning
> There shall be an additional section in DCF with the entry `DeviceComissioning`...

I think, this is intended, keyword in the standard can't just change.

**Comment by thesummer** [comment]
I also just noticed that according to the standard the keys are not case sensitive. So strictly speaking this change wasn't even necessary. Sorry for the noise.

**Comment by trojanobelix** [comment]
It's okay, it can be good that others don't fit the standard. It doesn't hurt and I still had some life time left. :-)
