### ISSUE TITLE
UI: TPDO and RPDO mapping does not show up the byte information

### ISSUE THREAD

**Issue by rohinidr** [CANopenNode/CANopenEditor#50]
![image](https://user-images.githubusercontent.com/37817230/228961181-8647da37-77e4-4a34-9900-17c3f757a5e7.png)
![image](https://user-images.githubusercontent.com/37817230/228961207-7be333dd-16bd-4872-a423-5a9c4170716b.png)

**Comment by trojanobelix** [comment]
Strange. Your version info is unknown. What version do you use? OS? XDD? Can you provide more detailed information?

**Comment by rohinidr** [comment]
> Strange. Your version info is unknown. What version do you use? OS? XDD? Can you provide more detailed information?

I am using Windows 11 . Its virtual machine on MAC (Parallels to be more specific).

**Comment by trojanobelix** [comment]
![image](https://user-images.githubusercontent.com/15106425/229055377-556ae510-6874-4f09-a2e9-7cd0b5571762.png)

And the Editor version? Seems that you are not using the latest binaries. Should look like:

![image](https://user-images.githubusercontent.com/15106425/229056208-53e45906-b22a-4f09-8fc6-102990758513.png)

**Comment by rohinidr** [comment]
After trying everything , I just figured out it was the issue with my display resolution ! I am able to see the byte information
