### ISSUE TITLE
Project saves always with the default data

### ISSUE THREAD

**Issue by killdaclick** [CANopenNode/CANopenEditor#51]
The issue is clearly visible in the following video:
https://youtu.be/V2HeW5CfOvE

The new project is created and multiple fields are changed in 'Device info' area.
After saving the project using File->Save Project As or File->Save Project all the data fields are reverted to factory values before save and the file is saved with reverted data.
It is not possible to save the Project anyhow. 

It works the same when running native on Windows, Linux on Mono and Linux on Wine.

I was running binary version available here:
https://github.com/CANopenNode/CANopenEditor/archive/refs/heads/build.zip

Am I doing something wrong?

**Comment by killdaclick** [comment]
Ok, so one needs to press the Update button before the save. It was not obvious :)

**Comment by trojanobelix** [comment]
Self assigned: Check update behavior. Red color for update button on change of value.

**Comment by trojanobelix** [comment]
Please try the latest bugfix release 93d61ccf2dd36146d190ef55339da57a1faad158

**Comment by killdaclick** [comment]
Is it available as binary?

**Comment by trojanobelix** [comment]
[Bugfix.zip](https://github.com/CANopenNode/CANopenEditor/files/11306819/Bugfix.zip)

**Comment by trojanobelix** [comment]
No feedback, so close
