### ISSUE TITLE
An error occurred while exporting the OD file

### ISSUE THREAD

**Issue by songxiaopeng1** [CANopenNode/CANopenEditor#56]
I am new to canopen，An error occurred when I exported the .c.h file, how can I solve it, thanks！

**Comment by songxiaopeng1** [comment]
![1683883874237](https://github.com/CANopenNode/CANopenEditor/assets/38554894/90ed3204-d1ee-4082-9df4-c02ea0082ba3)
[LD2-CAN7030_V1.03.eds.txt](https://github.com/CANopenNode/CANopenEditor/files/11461635/LD2-CAN7030_V1.03.eds.txt)

**Comment by trojanobelix** [comment]
Please use upper case for $NODEID as descriped on DS306 (might be corrected on open file in the future)

**Comment by songxiaopeng1** [comment]
Thank you. I will try

**Comment by trojanobelix** [comment]
Should be fixed with the last commit. Will be reopened if not.
