### ISSUE TITLE
[Question] What does the domain data type mean?

### ISSUE THREAD

**Issue by Ashenoneq** [CANopenNode/CANopenEditor#59]
I want to define the object dictionary for firmware upgrade, but I don't know how to choose the data type. Should I use the domain type?

**Comment by trojanobelix** [comment]
Seems to be a good idea.
Please make an internet search for "‎CiA DS 301 V 4.0.2: CANopen pdf" and you might use the second link if it is a well known search engine an it is a link with a france top level domain ;-)
