### ISSUE TITLE
Column span out of the range of valid values (INT32)

### ISSUE THREAD

**Issue by MartinHolcik** [CANopenNode/CANopenEditor#70]
Hello,
regarding the issues with modules mentioned in Issue #69, I have adjusted original [Weidmuelelr's EDS file for UR20 distributed peripheries](https://mdcop.weidmueller.com/mediadelivery/asset/900_//49697?_ga=2.159111359.467547158.1695798617-1581987833.1694688939). Attempt to open my custom [WI133489V1_25_adjusted.txt](https://github.com/CANopenNode/CANopenEditor/files/12735564/WI133489V1_25_adjusted.txt) in CANopenEditor leads to this exception:
![image](https://github.com/CANopenNode/CANopenEditor/assets/111753186/d46297b9-3447-4ead-8412-31923704dcc5)
![image](https://github.com/CANopenNode/CANopenEditor/assets/111753186/1d2f50a6-7373-4965-bc86-d6bf0090e4a4)
Is there something wrong with my EDS? I took as an example [WAGO EDS file](https://www.wago.com/medias/750-914-XT.zip?context=bWFzdGVyfGRvd25sb2Fkc3wxNzY5ODU2fGFwcGxpY2F0aW9uL3ppcHxhRGhrTDJoa05TOHhNemt3TURZek1ESTVORFUxT0M4M05UQXRPVEUwWDFoVUxucHBjQXwxNmQxZTA4MDViYmMyZDRiYWNkODNiMDQ0MTBlNDNlNjVlM2ZlYmViOGUzNWRkYzU0OGEzODI0ZWFhZDA3ZTdh&attachment=true) (which doesn't throw exceptions in CANopenNode).

**Comment by trojanobelix** [comment]
There were many errors in your eds.
You can use the free edsChecker from Vector to check an EDS

Please try the corrected version. Maybe you must setup the PDO Mapping. I have mapped what I guess you would leike to map.
 
[WI133489V1_25_adjusted_corr.txt](https://github.com/CANopenNode/CANopenEditor/files/12801761/WI133489V1_25_adjusted_corr.txt)

**Comment by MartinHolcik** [comment]
Many thanks @trojanobelix
