### ISSUE TITLE
Layout of PDO tab oversize out of window.

### ISSUE THREAD

**Issue by Spider84** [CANopenNode/CANopenEditor#71]
In design view and runtime the width and height of PDO grid1 is oversize main window.

![image](https://github.com/CANopenNode/CANopenEditor/assets/1863325/00b25590-3360-4214-9ef5-3140bd1d263e)

![image](https://github.com/CANopenNode/CANopenEditor/assets/1863325/76ddf1ee-56b8-40ee-8fc1-65c1931258ea)

**Comment by trojanobelix** [comment]
The current display is a compromise of the font size and standard window size. When maximising the window, it will fit in most cases.

Other suggestions or PR that optimises the display are welcome.

**Comment by Spider84** [comment]
I use default windows fonts and sizes. Default build generates oversized layout and maximized window don't fit them.

**Comment by Spider84** [comment]
![image](https://github.com/CANopenNode/CANopenEditor/assets/1863325/d8d548d8-ed8a-46ec-b2b2-8a1cbefa9b6a)
![image](https://github.com/CANopenNode/CANopenEditor/assets/1863325/75de822c-d564-4bc8-8615-eac1df9ce7a4)
![image](https://github.com/CANopenNode/CANopenEditor/assets/1863325/4e9d60f5-5e8d-4895-a09b-238ea387d57c)

As you can see, layout change size (width) with main window size (width) but in design width of tableLayoutPanel1 must be more smaller to be compiled to rigth size.

And distance between Zoom buttons is increasing....
