### ISSUE TITLE
PDO Mapping 'Invalid' not work while 'Export CanOpenNode'

### ISSUE THREAD

**Issue by JarvisXing** [CANopenNode/CANopenEditor#79]
If check TX/RX PDO Mapping Invalid checkbox, COB in TX/RX PDO Mapping will change.
But COB-ID in Object Dictionary will not change. COB_IDUsedByTPDO is same as Object Dictionary in OD.c，
so PDO->valid is always zero.
Is it a bug or design?

**Comment by trojanobelix** [comment]
Seems to work as expected (Bugfix branch):

![image](https://github.com/CANopenNode/CANopenEditor/assets/15106425/ec432701-e588-4f10-bd3b-0dc16b4e1eb5)
![image](https://github.com/CANopenNode/CANopenEditor/assets/15106425/a972da6b-f3ed-4d53-9e57-a0565186fca1)


`    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x80000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x1388,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x03E8,
        .SYNCStartValue = 0x00
    },`

**Comment by JarvisXing** [comment]
thank you, my mistake. I didn't choose item.
